name: Trigger Update Contributors in frontend.mu

on:
  pull_request_target:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Update Contributors in frontend.mu website repository
        run: |
          # Set the required variables
          target_repo_owner="frontendmu" 
          target_repo_name="frontend.mu"  
          source_repo_name="${{ github.event.repository.name }}"
          event_type="trigger-workflow"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$target_repo_owner/$target_repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"source_repo\": \"$source_repo_name\", \"unit\": false, \"integration\": true}}"
